define([], function() {
  return {
    "PropertyPaneDescription": "Insert Request Configuration",
    "BasicGroupName": "Basic Properties",
    "TargetListFieldLabel": "Target List",

    "YesText": "Yes",
    "NoText": "No",

    "RequestTypeFieldLabel": "Pick one Request Type for Personal Data",
    "RequestTypeAccessLabel": "Access",
    "RequestTypeCorrectLabel": "Correct",
    "RequestTypeExportLabel": "Export",
    "RequestTypeObjectionLabel": "Objection",
    "RequestTypeEraseLabel": "Erase",

    "TitleFieldLabel": "Title",
    "TitleFieldPlaceholder": "Provide a Title for the Request",
    "TitleFieldValidationErrorMessage": "The length of the Title should be at leat 10 characters, actual is",
    "DataSubjectFieldLabel": "Data Subject",
    "DataSubjectFieldPlaceholder": "Provide a target Data Subject",
    "DataSubjectEmailFieldLabel": "Data Subject Email",
    "DataSubjectEmailFieldPlaceholder": "Provide a valid email address for the Data Subject",
    "DataSubjectEmailFieldValidationErrorMessage": "Please, provide a valid email address",
    "VerifiedDataSubjectFieldLabel": "Verified Data Subject",
    "RequestAssignedToFieldLabel": "Request Assigned To",
    "RequestAssignedToFieldPlaceholder": "Provide the assignee for the Request",
    "RequestInsertionDateFieldLabel": "Request Insertion Date",
    "RequestInsertionDateFieldPlaceholder": "Provide the Insertion Date of the Request",
    "RequestDueDateFieldLabel": "Request Due Date",
    "RequestDueDateFieldPlaceholder": "Provide the Due Date of the Request",
    "AdditionalNotesFieldLabel": "Additional Notes",
    "DeliveryMethodFieldLabel": "Delivery Method",
    "DeliveryMethodFieldPlaceholder": "Provide the Delivery Method for the Request",
    "CorrectionDefinitionFieldLabel": "Correction Definition",
    "DeliveryFormatFieldLabel": "Delivery Format",
    "DeliveryFormatFieldPlaceholder": "Provide the Delivery Format for the Request",
    "PersonalDataFieldLabel": "Personal Data",
    "ProcessingTypeFieldLabel": "Processing Type",
    "ProcessingTypeFieldPlaceholder": "Provide the Processing Type for the Request",
    "ReasonFieldLabel": "Reason",
    "NotifyApplicableFieldLabel": "Notify Applicable Controllers /Processors & Sub Processors",

    "SaveButtonText": "Save",
    "CancelButtonText": "Cancel",
    "ItemSavedMessage": "Item saved!",
    "InsertNextLabel": "Insert next",
    "GoHomeLabel": "Go home",
    "ItemInsertedDialogTitle": "Item inserted",
    "ItemInsertedDialogSubText": "Your item has been inserted. Now you can add another one, or you can go back to the home page.",
  }
});