define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",

    "YesText": "Yes",
    "NoText": "No",

    "EventTypeFieldLabel": "Pick one Event/Incident Type for Personal Data",
    "EventTypeDataBreachLabel": "Data Breach",
    "EventTypeIdentityRiskLabel": "Identity Risk",
    "EventTypeDataConsentLabel": "Data Consent",
    "EventTypeDataConsentWithdrawalLabel": "Data Consent Withdrawal",
    "EventTypeDataProcessingLabel": "Data Processing",
    "EventTypeDataArchivedLabel": "Data Archived",

    "TitleFieldLabel": "Title",
    "TitleFieldPlaceholder": "Provide a Title for the Event",
    "TitleFieldValidationErrorMessage": "The length of the Title should be at leat 10 characters, actual is",
    "NotifiedByFieldLabel": "Notified By",
    "NotifiedByFieldPlaceholder": "Provide a description of who notified the Event",
    "NotifiedByFieldValidationErrorMessage": "The length of the Notified By should be at least 5 characters, actual is",
    "EventAssignedToFieldLabel": "Event Assigned To",
    "EventAssignedToFieldPlaceholder": "Provide the assignee of the Event",
    "EventStartDateFieldLabel": "Event Start Date",
    "EventStartDateFieldPlaceholder": "Provide the Start Date of the Event",
    "EventStartTimeHoursFieldLabel": "Hours",
    "EventStartTimeMinutesFieldLabel": "Minutes",
    "EventEndDateFieldLabel": "Event End Date",
    "EventEndDateFieldPlaceholder": "Provide the End Date of the Event",
    "EventEndTimeHoursFieldLabel": "Hours",
    "EventEndTimeMinutesFieldLabel": "Minutes",
    "PostEventReportFieldLabel": "Post Event/Incident Report",
    "AdditionalNotesFieldLabel": "Additional Notes",
    "BreachTypeFieldLabel": "Breach Type",
    "BreachTypeFieldPlaceholder": "Select the Breach Type",
    "SeverityFieldLabel": "Severity",
    "SeverityFieldPlaceholder": "Select the Severity level",
    "DPANotifiedFieldLabel": "DPA Notified",
    "DPANotificationDateFieldLabel": "DPA Notification Date",
    "DPANotificationDateFieldPlaceholder": "Provide the DPA Notification date",
    "DPANotificationTimeHoursFieldLabel": "Hours",
    "DPANotificationTimeMinutesFieldLabel": "Minutes",
    "EstimatedAffectedSubjectsFieldLabel": "Estimated Number of Affected Data Subjects",
    "EstimatedAffectedSubjectsFieldValidationErrorMessage": "Please, provide a valid number",
    "ToBeDeterminedFieldLabel": "To Be Determined",
    "IncludesChildrenFieldLabel": "Includes Children",
    "IncludesChildrenInProgressFieldLabel": "In Progress",
    "ActionPlanFieldLabel": "Action Plan",
    "BreachResolvedFieldLabel": "Breach Resolved",
    "ActionsTakenFieldLabel": "Actions Taken",
    "RiskTypeFieldLabel": "Risk Type",
    "RiskTypeFieldPlaceholder": "Select the Risk Type",
    "IncludesSensitiveDataFieldLabel": "Includes Sensitive Data",
    "IncludesSensitiveDataFieldPlaceholder": "Select any included Sensitive Data",
    "DataSubjectIsChildFieldLabel": "Data Subject is Child",
    "IndirectDataProviderFieldLabel": "Indirect Data Provider",
    "DataProviderFieldLabel": "Data Provider",
    "ConsentNotesFieldLabel": "Consent Notes",
    "ConsentTypeFieldLabel": "Consent Type",
    "ConsentTypeFieldPlaceholder": "Select the Consent Types",
    "ConsentIsInternalFieldLabel": "Internal or External Data Subject",
    "InternalConsentText": "Internal",
    "ExternalConsentText": "External",
    "ConsentWithdrawalTypeFieldLabel": "Withdrawal Type",
    "ConsentWithdrawalTypeFieldPlaceholder": "Select the Withdrawal Type",
    "ConsentWithdrawalNotesFieldLabel": "Withdrawal Notes",
    "OriginalConsentAvailableFieldLabel": "Original Consent Available",
    "OriginalConsentFieldLabel": "Original Consent",
    "OriginalConsentFieldPlaceholder": "Select the Original Consent",
    "NotifyApplicableFieldLabel": "Notify Applicable Controllers /Processors & Sub Processors",
    "ProcessingTypeFieldLabel": "Processing Type",
    "ProcessingTypeFieldPlaceholder": "Select the Processing Type",
    "ProcessorsFieldLabel": "GDPR Processors",
    "ProcessorsFieldPlaceholder": "Select the GDPR Processors",
    "ArchivedDataFieldLabel": "Archived Data",
    "AnonymizeFieldLabel": "Anonymize",
    "ArchivingNotesFieldLabel": "Archiving Notes",

    "SaveButtonText": "Save",
    "CancelButtonText": "Cancel",
    "ItemSavedMessage": "Item saved!",
    "InsertNextLabel": "Insert next",
    "GoHomeLabel": "Go home",
    "ItemInsertedDialogTitle": "Item inserted",
    "ItemInsertedDialogSubText": "Your item has been inserted. Now you can add another one, or you can go back to the home page.",

    "HoursValidationError": "Please provide a valid hours value",
    "MinutesValidationError": "Please provide a valid minutes value",
  }
});